# SPDX-FileCopyrightText: 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0
labelPRBasedOnFilePath:
    ############################################################
    #  Top Level Labels
    ############################################################
    repo:
        - ./*

    ############################################################
    #  Examples
    ############################################################
    examples:
        - examples/*

    ############################################################
    #  Documentation
    ############################################################
    documentation:
        - docs/*

    ############################################################
    #  Tools + Development Items
    ############################################################
    scripts:
        - scripts/*

    integrations:
        - integrations/*

    vscode:
        - .vscode
        - .devcontainer

    gn:
        - gn/*

    github:
        - .github

    workflows:
        - .github/workflows/*

    tools:
        - tools/*

    ############################################################
    #  Source Code
    ############################################################
    qr code:
        - src/qrcode/*

    lwip:
        - src/lwip/*

    inet:
        - src/inet/*

    config:
        - config/*

    lib:
        - src/lib/*

    crypto:
        - src/crypto/*

    controller:
        - src/controller/*

    ble:
        - src/ble/*

    app:
        - src/app/*

    transport:
        - src/transport/*

    system:
        - src/system/*

    setup payload:
        - src/setup_payload/*

    ############################################################
    #  Platforms
    ############################################################
    platform:
        - src/platform/*

    darwin:
        - src/platform/Darwin/*
        - src/darwin/*

    efr32:
        - src/platform/efr32/*

    esp32:
        - src/platform/ESP32/*

    freeRTOS:
        - src/platform/FreeRTOS/*

    k32w:
        - src/platform/K32W/*

    linux:
        - src/platform/Linux/*

    nrf connect:
        - src/platform/nrfconnect/*

    openthread:
        - src/platform/openthread/*

    zephyr:
        - src/platform/Zephyr/*

    telink:
        - src/platform/telink/*
