# SPDX-FileCopyrightText: 2020-2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

# To run locally:
#   Prerequisits (only once):
#
#      apt-get install aspell aspell-en
#      pip install pyspelling
#
#   Actual run:
#
#      pyspelling pyspelling --config .spellcheck.yml

matrix:
  - name: markdown
    dictionary:
      wordlists:
        - .github/.wordlist.txt
    pipeline:
      # See https://facelessuser.github.io/pyspelling/configuration/#pipeline
      # and https://facelessuser.github.io/pyspelling/filters/context/

      # context-aware logic: we have a LOT of code examples in markdown,
      # avoid trying to spellcheck code.
      - pyspelling.filters.context:
          context_visible_first: true
          escapes: \\[\\`~]
          delimiters:
          # Ignore multiline content between fences (fences can have 3 or more back ticks)
          # ```
          # content
          # ```
          #
          # Allows language marker (since github allows it) like:
          # ```python
          # content
          # ```
          #
          # Allow MyST extended syntax like:
          # ```{include} my/file.md
          # ```
          - open: '(?s)^(?P<open> *`{3,})([a-z]*$|{[a-z]*?}\s*[^\n]*?$)'
            close: '^(?P=open)$'
          # Ignore text between inline back ticks
          - open: '(?P<open>`+)'
            close: '(?P=open)'
          # Ignore URL in hyperlinks [title](url)
          - open: '\[[^]]*\]\('
            close: '\)'
          # Ignore code markers
          - open: '<code>'
            close: '</code>'

      # converts markdown to HTML
      - pyspelling.filters.markdown:
    sources:
      - '**/*.md|!third_party/**|!examples/common/**/repo/**|!docs/ERROR_CODES.md'
    aspell:
      ignore-case: true
