#
# SPDX-FileCopyrightText: (c) 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0
#

name: connectedhomeip
build:
    cmake: .
    kconfig: Kconfig
    depends:
        - nrfxlib
        - openthread
