# SPDX-FileCopyrightText: 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Bloat Check
on:
    schedule:
        - cron: "*/5 * * * *"

concurrency:
    group: ${{ github.workflow }}
    # Don't cancel an already-running bloat check just because it took more
    # than 5 minutes to run and our cron job is trying to schedule a new one.
    cancel-in-progress: false

jobs:
    pull_request_update:
        name: Report on pull requests

        # Don't run on forked repos
        if: github.repository_owner == 'project-chip'

        runs-on: ubuntu-latest

        container:
            image: ghcr.io/project-chip/chip-build:1

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Report
              run: |
                  scripts/tools/memory/gh_report.py \
                    --verbose \
                    --report-increases 0.2 \
                    --report-pr \
                    --github-comment \
                    --github-limit-artifact-pages 50 \
                    --github-limit-artifacts 500 \
                    --github-limit-comments 20 \
                    --github-repository project-chip/connectedhomeip \
                    --github-api-token "${{ secrets.GITHUB_TOKEN }}"
