# SPDX-FileCopyrightText: (c) 2020-2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Docker CHIP images

on:
    push:
        paths:
            - "integrations/docker/images/**"
    pull_request:
        paths:
            - "integrations/docker/images/**"
    workflow_dispatch:

jobs:
    build_images:
        name: Build Docker CHIP Build images
        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'
        strategy:
            fail-fast: false
            matrix:
                img:
                    - ""
                    - "-ameba"
                    - "-android"
                    - "-cirque"
                    - "-crosscompile"
                    - "-doxygen"
                    - "-efr32"
                    - "-esp32"
                    - "-esp32-qemu"
                    - "-infineon"
                    # NOTE: imx image requires too much space for GitHub-hosted runners. It fails with:
                    # ```
                    # ....
                    # ApplyLayer exit status 1 stdout:  stderr: write /opt/fsl-imx-xwayland/5.15-kirkstone/sysroots/armv8a-poky-linux/opt/ltp/testcases/bin/fanotify15: no space left on device
                    # ```
                    # - "-imx"
                    - "-k32w"
                    - "-mbed-os"
                    - "-nrf-platform"
                    - "-telink"
                    - "-ti"
                    - "-tizen"
                    - "-openiotsdk"
                    # NOTE: vscode image consumes ~52 GB disk space but GitHub-hosted runners provide ~10 GB free disk space(https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
                    #- "-vscode"
                    - "-zap"
        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - name: Build All images using project bash script
              run: |
                  cd integrations/docker/images/chip-build${{ matrix.img }}
                  ./build.sh --latest
