# SPDX-FileCopyrightText: (c) 2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Build example - Tizen

on:
    push:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
    tizen:
        name: Tizen
        env:
            BUILD_TYPE: tizen

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: connectedhomeip/chip-build-tizen:0.6.05
            options: --user root
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"
                - "/tmp/output_binaries:/tmp/output_binaries"

        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - name: Checkout submodules
              run: scripts/checkout_submodules.py --shallow --platform tizen
            - name: Build Tizen examples
              run: |
                ./scripts/run_in_build_env.sh \
                    "./scripts/build/build_examples.py \
                        --enable-flashbundle \
                        --target tizen-arm-all-clusters \
                        --target tizen-arm-all-clusters-minimal-no-wifi \
                        --target chip-tool \
                        --target light \
                        --target light-no-ble-no-wifi \
                        build \
                        --copy-artifacts-to out/artifacts \
                    "
