# SPDX-FileCopyrightText: 2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Build example - Tizen

on:
    push:
    pull_request:
    merge_group:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true

jobs:
    tizen:
        name: Tizen

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: ghcr.io/project-chip/chip-build-tizen:1
            options: --user root
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"
                - "/tmp/output_binaries:/tmp/output_binaries"

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                platform: tizen

            - name: Build Tizen examples
              run: |
                  ./scripts/run_in_build_env.sh \
                      "./scripts/build/build_examples.py \
                          --enable-flashbundle \
                          --target tizen-arm-all-clusters \
                          --target tizen-arm-chip-tool-ubsan \
                          --target tizen-arm-light \
                          build \
                          --copy-artifacts-to out/artifacts \
                      "
