# SPDX-FileCopyrightText: (c) 2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Pick Fixit Rotation

on:
    workflow_dispatch:

jobs:
    shuffle_names:
        name: Shuffle names
        runs-on: ubuntu-latest

        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      submodules: true
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - name: Pick fixit rotation order
              run: scripts/fixit_rotation.py
