# SPDX-FileCopyrightText: 2023 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Minimal Build (Linux / configure)

on:
    push:
    pull_request:
    merge_group:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
    minimal:
        name: Linux / configure build of all-clusters-app

        if: github.actor != 'restyled-io[bot]'
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/project-chip/chip-build-minimal:1

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Checkout submodules # but don't bootstrap!
              uses: ./.github/actions/checkout-submodules
              with:
                platform: linux

            - name: Configure and build All Clusters App
              run: |
                  CC=gcc CXX=g++ scripts/configure --project=examples/all-clusters-app/linux && ./ninja-build
