# SPDX-FileCopyrightText: 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Recent Fail Summary
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}

jobs:
  list_workflows:
    name: Summarize Recent Workflow Failures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install pandas python-slugify
      - name: Run Summarization Script
        run: python scripts/tools/summarize_fail.py
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: workflow-fail-summary
          path: |
            run_list.json
            recent_fails.csv
            recent_fails_frequency.csv
            recent_fails_logs
          retention-days: 5
        
