# SPDX-FileCopyrightText: (c) 2020-2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Run misspell

on:
    push:
        paths:
            - "**.md"
            - ".github/.wordlist.txt"
    pull_request:
        paths:
            - "**.md"
            - ".github/.wordlist.txt"

jobs:
    check-reviewdog:
        name: Check Spelling - reviewdog
        runs-on: ubuntu-latest
        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - uses: reviewdog/action-misspell@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
    check-spellcheck:
        name: Check Spelling - pyspelling
        runs-on: ubuntu-latest
        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - uses: igsekor/pyspelling-any@v0.0.2
