# SPDX-FileCopyrightText: 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: ZAP - Regenerate

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true
    
jobs:
    zap_regeneration:
        name: ZAP Regeneration

        runs-on: ubuntu-20.04
        container:
            image: ghcr.io/project-chip/chip-build:1
        defaults:
            run:
                shell: sh
        if: github.actor != 'restyled-io[bot]'

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                submodules: true
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                platform: linux

            - name: Generate all
              run: ./scripts/run_in_build_env.sh scripts/tools/zap_regen_all.py
            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: Regenerating ZAP
