# SPDX-FileCopyrightText: (c) 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

name: ZAP

on:
    push:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
    zap_templates:
        name: ZAP templates generation
        timeout-minutes: 90

        runs-on: ubuntu-20.04
        container:
            image: connectedhomeip/chip-build-zap:0.6.05
        defaults:
            run:
                shell: sh
        if: github.actor != 'restyled-io[bot]'

        steps:
            - uses: Wandalen/wretry.action@v1.0.15
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - name: Checkout submodules
              run: scripts/checkout_submodules.py --shallow --platform linux
            - name: Setup ZAP
              timeout-minutes: 10
              run: |
                  cd third_party/zap/repo/
                  npm ci
                  npm run version-stamp
                  npm rebuild canvas --update-binary
                  npm run build-spa
            - name: Generate all
              run: scripts/tools/zap_regen_all.py
            - name: Check for uncommited changes
              run: |
                  git add .
                  # Show the full diff
                  git diff-index -p HEAD --
                  # Also show just the files that are different, to make it easy
                  # to tell at a glance what might be going on.  And throw in
                  # --exit-code to make this job fail if there is a difference.
                  git diff-index --exit-code HEAD --
